#!/bin/bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew bundle install

chsh -s /usr/local/bin/fish

xargs -L 1 code --install-extension < vscode-extensions.txt


cp other/config ~/.gitconfig
