name: GitHub Actions CI
on:
  push:
    branches: main
  pull_request:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Validate syntax
        run: bash -n setup
